const kosts = [
  {
    id: 1,
    judul: "Kost Cewek",
    tipe: "Kost Putri",
    daerah: "Karangbesuki",
    alamat: "Jalan Candi 3, RT 01/ RW 03",
    kepadatan: "2 kamar/lt",
    harga: 600000,
    kelayakan_tinggal: 66.66,
    listrik: "Pemadaman listrik jarang terjadi",
    air: "Air dalam keadaan bersih",
    bau: "Jarang tercium bau tidak sedap",
    kontak: "https://wa.me/6285736025553",
    gambar_kamarmandi: "Kost/KamarMandi1.jpg",
    gambar_kamartidur: "Kost/Kamar1.jpg",
    lat: -7.94324,
    long: 112.63905,
  },
  {
    id: 2,
    judul: "Kost Bu Ani",
    tipe: "Kost Putri",
    daerah: "Sumbersari",
    alamat: "Jl. Veteran dalam",
    kepadatan: "6 kamar/lt",
    harga: 400000,
    kelayakan_tinggal: 66.66,
    listrik: "Pemadaman listrik jarang terjadi",
    air: "Air dalam keadaan bersih",
    bau: "Jarang tercium bau tidak sedap",
    kontak: "https://wa.me/6285607933009",
    gambar_kamarmandi: "Kost/KamarMandi2.jpg",
    gambar_kamartidur: "Kost/Kamar2.jpg",
    lat: -7.95691,
    long: 112.61618,
  },
  {
    id: 3,
    judul: "Kost Pak Udin",
    tipe: "Kost Putra",
    daerah: "Jatimulyo",
    alamat: "Jl bunga kumis kucing",
    kepadatan: "2 kamar/lt",
    harga: 500000,
    kelayakan_tinggal: 66.66,
    listrik: "Pemadaman listrik jarang terjadi",
    air: "Air dalam keadaan bersih",
    bau: "Jarang tercium bau tidak sedap",
    kontak: "https://wa.me/6281343254400",
    gambar_kamarmandi: "Kost/KamarMandi3.jpg",
    gambar_kamartidur: "Kost/Kamar3.jpg",
    lat: -7.95223,
    long: 112.62204,
  },
  {
    id: 4,
    judul: "Kost 86 Landungsari",
    tipe: "Kost Putri",
    daerah: "Landungsari",
    alamat: "Jl. Tirto Utomo",
    kepadatan: "7 kamar/lt",
    harga: 650000,
    kelayakan_tinggal: 83.33,
    listrik: "Pemadaman listrik jarang terjadi",
    air: "Air dalam keadaan bersih",
    bau: "Tidak pernah tercium bau tidak sedap",
    kontak: "https://wa.me/6281334555152",
    gambar_kamarmandi: "Kost/KamarMandi4.jpg",
    gambar_kamartidur: "Kost/Kamar4.jpg",
    lat: -7.92573,
    long: 112.59552,
  },
  {
    id: 5,
    judul: "Kost Sakinah",
    tipe: "Kost Putri",
    daerah: "Karangbesuki",
    alamat: "Jl. Sigura-gura Barat",
    kepadatan: "10 kamar/lt",
    harga: 600000,
    kelayakan_tinggal: 53.33,
    listrik: "Pemadaman listrik sering terjadi",
    air: "Air dalam keadaan bersih",
    bau: "Jarang tercium bau tidak sedap",
    kontak: "https://wa.me/6281336864188",
    gambar_kamarmandi: "Kost/KamarMandi5.jpg",
    gambar_kamartidur: "Kost/Kamar5.jpg",
    lat: -7.95769,
    long: 112.60532,
  },
  {
    id: 6,
    judul: "Kost Pak Bram",
    tipe: "Kost Putri",
    daerah: "Sumbersarii",
    alamat: "Jl. Terusan Ambarawa Gang 5 no 4",
    kepadatan: "10 kamar/lt",
    harga: 480000,
    kelayakan_tinggal: 41.66,
    listrik: "Pemadaman listrik sering terjadi",
    air: "Air dalam keadaan bersih",
    bau: "Sering tercium bau tidak sedap",
    kontak: "https://wa.me/6281334555152",
    gambar_kamarmandi: "Kost/KamarMandi6.jpg",
    gambar_kamartidur: "Kost/Kamar6.jpg",
    lat: -7.9488,
    long: 112.65301,
  },
  {
    id: 7,
    judul: "Kost Putri Royal 5",
    tipe: "Kost Putri",
    daerah: "Karangbesuki",
    alamat: "Jl. Bendungan Sigura-gura Barat 3",
    kepadatan: "7 kamar/lt",
    harga: 1000000,
    kelayakan_tinggal: 83.33,
    listrik: "Pemadaman listrik jarang terjadi",
    air: "Air dalam keadaan bersih",
    bau: "Tidak pernah tercium bau tidak sedap",
    kontak: "https://wa.me/62818538627",
    gambar_kamarmandi: "Kost/KamarMandi7.jpg",
    gambar_kamartidur: "Kost/Kamar7.jpeg",
    lat: -7.95722,
    long: 112.61216,
  },
];

export default kosts;
